In [1]:
import cv2

In [2]:
cv2.__version__

'4.0.1'

### Read and Write Image

- *`cv2.imread() does not give error even if we give wrong image name as input.`*
- For wrong file name *img* variable will have **None** value

In [3]:
#Second argument is flag
img = cv2.imread('lena.jpg',-1) #As it is
print('cv2.IMREAD_UNCHANGED',cv2.IMREAD_UNCHANGED)

cv2.imshow('image',img) #for showing image and 'image' is window name
cv2.waitKey(10000) # waiting for image to show i.e. image will be shown for 10 seconds further i.e. 10,000 ms
cv2.destroyAllWindows() #destorying all windows

cv2.IMREAD_UNCHANGED -1


In [4]:
img = cv2.imread('lena.jpg',0) #Grayscale
print('cv2.IMREAD_GRAYSCALE',cv2.IMREAD_GRAYSCALE)

cv2.imshow('image',img) #for showing image and 'image' is window name
cv2.waitKey(10000) # waiting for image to show i.e. image will be shown for 10 seconds further i.e. 10,000 ms
cv2.destroyAllWindows() #destorying all windows

cv2.IMREAD_GRAYSCALE 0


In [5]:
img = cv2.imread('lena.jpg',1) #Color
print('cv2.IMREAD_COLOR',cv2.IMREAD_COLOR)

cv2.imshow('image',img) #for showing image and 'image' is window name
cv2.waitKey(10000) # waiting for image to show i.e. image will be shown for 10 seconds further i.e. 10,000 ms
cv2.destroyAllWindows() #destorying all windows

cv2.IMREAD_COLOR 1


**Fun Fact**
- If we give "zero" as an argument to waitKey(), than it will show image for infinite time *until we click close button*

**Question**
- What is the difference between already coloured image and cv2.IMREAD_COLOR?

In [6]:
img = cv2.imread('lena.jpg',0)
cv2.imwrite('lean_grayscale.png',img) #new file is created

True

In [7]:
cv2.imshow('image',cv2.imread('lean_grayscale.png',-1))
cv2.waitKey(0)
cv2.destroyAllWindows()

**Making things better**

In [8]:
img = cv2.imread('lean_grayscale.png',-1)
cv2.imshow('image',img)
key_pressed = cv2.waitKey(0) & 0xFF #for safe side for 64bit machine we are adding mask

if key_pressed == ord('s'): #s is pressed create new file
    cv2.imwrite('lean_grayscale.png',img)
    print("New file created")
else:
    print("Just destroying all windows")
cv2.destroyAllWindows()    

Just destroying all windows


### Drawing shape over Images

**Drawing line**

In [9]:
img = cv2.imread('lena.jpg',1)
cv2.imwrite('lena_line.png',img)

img = cv2.imread('lena_line.png',1)

img = cv2.line(img, (0,0), (255,255), (0,255,0), 5) 
# arguments (image, x_coor, y_coor, colour in BGR format, thickness)

cv2.imshow('image',img)
cv2.waitKey(0)

cv2.imwrite('lena_line.png',img) #finally saving pic again

cv2.destroyAllWindows()

**Arrowed Line**

In [10]:
img = cv2.imread('lena.jpg',1)
cv2.imwrite('lena_arrowed_line.png',img)

img = cv2.imread('lena_arrowed_line.png',1)

img = cv2.arrowedLine(img, (0,255), (255,255), (255,255,0), 5) 
# arguments (image, x_coor, y_coor, colour in BGR format, thickness)

cv2.imshow('image',img)
cv2.waitKey(0)

cv2.imwrite('lena_arrowed_line.png',img) #finally saving pic again

cv2.destroyAllWindows()

**Rectangle**

In [11]:
img = cv2.imread('lena.jpg',1)
cv2.imwrite('lena_rectangle.png',img)

img = cv2.imread('lena_rectangle.png',1)

'''
x1,y1---------
|            |
|            |
|            |
---------x2,y2

'''

img = cv2.rectangle(img, (100,100), (255,255), (255,255,0), 5)
# arguments (image, top_left_coor, bottom_right_coor, colour in BGR format, thickness)

cv2.imshow('image',img)
cv2.waitKey(0)

img = cv2.rectangle(img, (100,100), (255,255), (255,55,0), -1) #filled rectangle

cv2.imshow('image',img)
cv2.waitKey(0)

cv2.imwrite('lena_rectangle.png',img) #finally saving pic again

cv2.destroyAllWindows()

**Circle**

In [12]:
img = cv2.imread('lena.jpg',1)
cv2.imwrite('lena_circle.png',img)

img = cv2.imread('lena_circle.png',1)

img = cv2.circle(img, (255,255), 150, (255,0,255), 5) 
# arguments (image, center, radius, colour in BGR format, thickness)

cv2.imshow('image',img)
cv2.waitKey(0)

img = cv2.circle(img, (255,255), 150, (255,0,255), -1) #filled circle

cv2.imshow('image',img)
cv2.waitKey(0)

cv2.imwrite('lena_circle.png',img) #finally saving pic again

cv2.destroyAllWindows()

**Putting Text**

In [13]:
img = cv2.imread('lena.jpg',1)
cv2.imwrite('lena_text.png',img)

img = cv2.imread('lena_text.png',1)

font = cv2.FONT_HERSHEY_SIMPLEX

img = cv2.putText(img, 'My first Text', (30,100), font, 2, (0,0,0), 5, cv2.LINE_AA) 
# arguments (image, Text_to_write, starting_coor, font_face, font_size, font_color, thickness, line_type)

cv2.imshow('image',img)
cv2.waitKey(0)

cv2.imwrite('lena_text.png',img) #finally saving pic again

cv2.destroyAllWindows()

**Create your own Image using Numpy zeros method instead of imread()**

In [2]:
import numpy as np

In [15]:
img = np.zeros([512, 512, 3], np.uint8) #arguments (image size, dtype)
#[height, width, 3], 3 for black n white image

img = cv2.line(img, (0,0), (255,255), (0,255,0), 5) 
img = cv2.arrowedLine(img, (0,255), (255,255), (255,255,0), 5) 
img = cv2.rectangle(img, (100,100), (255,255), (255,255,0), 5)
img = cv2.circle(img, (255,255), 150, (255,0,255), 5) 

font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img, 'My first Text', (30,100), font, 2, (255,255,255), 5, cv2.LINE_AA) 

cv2.imshow('image',img)
cv2.waitKey(0)

cv2.imwrite('own_image.png',img) #finally saving pic again

cv2.destroyAllWindows()

**Explore**
- `cv2.polylines` for drawing polygons
- `cv2.ellipse` for drawing ellipse

### Capturing from live camera

In [16]:
cap = cv2.VideoCapture(0)
# argument (input_video_file_directly OR camera_input)
# default camera is 0 or -1

# while loop to capture frame continuously
while True:
    BOOL, frame = cap.read() # returns True or False if frame is available and frame with it
    
    cv2.imshow('video',frame)
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'): #close only if q is pressed
        break

cap.release() # releasing all resources
cv2.destroyAllWindows()

**In Gray scale**

In [15]:
cap = cv2.VideoCapture(0)
# argument (input_video_file_directly OR camera_input)
# default camera is 0 or -1

# while loop to capture frame continuously
while True:
    BOOL, frame = cap.read() # returns True or False if frame is available and frame with it
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # BGR is converted to Gray
    
    cv2.imshow('video',gray)
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'): #close only if q is pressed
        break

cap.release() # releasing all resources
cv2.destroyAllWindows()

- Now instead of writing `while True` cap has one method called `cap.isOpened()` which will return *boolean* value and directly run the code and nothing will happen if file name or camera index number is wrong.
- We can also change the above code too.

**Reading Video file**

In [8]:
cap = cv2.VideoCapture('My_video.mp4')

while cap.isOpened():
    BOOL, frame = cap.read()
    
    cv2.imshow('my_video', frame)
    key_pressed = cv2.waitKey(10) & 0xFF
    
    if key_pressed == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

- cap also have many other properties eg. you can get **height and width** too 

In [13]:
# cap = cv2.VideoCapture(0)
cap = cv2.VideoCapture("My_video.mp4")

while cap.isOpened():
    BOOL, frame = cap.read()
    
    # print(cap.get(cv2.CAP_PROP_FRAME_WIDTH), cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) 
    # argument prop values
    
    frame = cv2.rectangle(frame, (100,100), (255,255), (0,0,255), 5)
    
    cv2.imshow('my_video', frame)
    key_pressed = cv2.waitKey(10) & 0xFF
    
    if key_pressed == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

**Saving Video**

In [6]:
cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
output = cv2.VideoWriter("output_video.avi", fourcc, 20.0, (640,480))
# arguments (output_filename, fourcc, frames per second, width and height)

while cap.isOpened():
    BOOL, frame = cap.read()
    
    if BOOL:

        output.write(frame) # saving video

        cv2.imshow("new_video",frame)
        key_pressed = cv2.waitKey(1) & 0xFF

        if key_pressed == ord('q'):
            break
    else:
        break
        
cap.release()
output.release()
cv2.destroyAllWindows()

`https://www.fourcc.org/codecs.php`

**Setting Camera Parameters**

In [6]:
cap = cv2.VideoCapture(0)
# cap = cv2.VideoCapture("My_video.mp4")

while True:
    BOOL, frame = cap.read()
    
    # set any property which you can get
#     cap.set(cv2.CAP_PROP_FRAME_WIDTH, 620)
#     cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
    '''not working in mine
    Do not know why?'''
    frame = cv2.rectangle(frame, (100,100), (255,255), (0,0,255), 5)
    
    cv2.imshow('my_video', frame)
    key_pressed = cv2.waitKey(1) & 0xFF
    
    if key_pressed == ord('q'):
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH), cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) 
        # argument prop values
        break
    
cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.0.1) C:\ci\opencv-suite_1573470242804\work\modules\highgui\src\window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


**Showing height, width and current time in video**

In [1]:
import datetime

In [7]:
cap = cv2.VideoCapture(0)

while cap.isOpened():
    BOOL, frame = cap.read()
    
    font = cv2.FONT_HERSHEY_SIMPLEX
    
    text = "Width: " + str(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) + " Height: " + str(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    date_n_time = str(datetime.datetime.now())
    
    # arguments (image, Text_to_write, starting_coor, font_face, font_size, font_color, thickness, line_type)
    frame = cv2.putText(frame, text, (10,50), font, 1, (0,255,255), 2, cv2.LINE_AA)
    frame = cv2.putText(frame, date_n_time, (10,100), font, 1, (255,0,255), 2, cv2.LINE_AA)
    
        
    cv2.imshow('my_video', frame)
    key_pressed = cv2.waitKey(1) & 0xFF
    
    if key_pressed == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

**More Image properties**

In [5]:
img = cv2.imread('messi5.jpg',-1)

print("no. of row, column, channels => ",img.shape) # returns tuple
print("total no. of pixel => ",img.size)
print("image datatype => ",img.dtype)

no. of row, column, channels =>  (342, 548, 3)
total no. of pixel =>  562248
image datatype =>  uint8


**Splitting the image into 3 channels**

In [11]:
b, g, r = cv2.split(img)
print("b: ", b, "\n\n", "g: ", g, "\n\n", "r: ", r)

b:  [[39 42 44 ... 59 57 54]
 [37 42 46 ... 62 60 57]
 [42 47 51 ... 64 63 60]
 ...
 [56 48 49 ... 60 63 74]
 [52 59 50 ... 56 69 66]
 [43 58 72 ... 49 50 51]] 

 g:  [[ 43  46  47 ...  54  52  49]
 [ 41  45  49 ...  60  58  55]
 [ 45  50  54 ...  63  62  60]
 ...
 [143 133 129 ... 133 134 144]
 [139 141 130 ... 132 142 137]
 [129 140 150 ... 124 125 124]] 

 r:  [[ 44  47  51 ...  55  53  50]
 [ 42  49  54 ...  60  58  55]
 [ 49  55  62 ...  65  64  60]
 ...
 [ 99  89  86 ...  93  94 104]
 [ 95  98  87 ...  91 102  97]
 [ 87  98 109 ...  86  87  86]]


**You can merge b,g,r to make an image**

In [16]:
img = cv2.merge((b,g,r)) # given argument as tuple
cv2.imshow('messi',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Trackbars

Trackbars are useful when we want to change anything into our image **Dynamically** at runtime.

In [3]:
def blue(x):
    print("Blue",x) # x is current position

def green(x):
    print("Green",x) # x is current position
    
def red(x):
    print("Red",x) # x is current position

In [10]:
img = np.zeros((300,512,3), np.uint8)
cv2.namedWindow('window_image') # creates window with a name

cv2.createTrackbar('Blue', 'window_image', 0, 255, blue)
# arguments (Trackbar_name, name_of_window, initial_value_where_trackbar_will_be_set, count_final_value, callback_function)
# trackbar name because we can have multiple trackbars in a window

cv2.createTrackbar('Green', 'window_image', 0, 255, green)
cv2.createTrackbar('Red', 'window_image', 0, 255, red)

while(1):
    cv2.imshow('window_image',img)
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
    b = cv2.getTrackbarPos('Blue','window_image') # arguments (trackbar_name, window_name)
    g = cv2.getTrackbarPos('Green','window_image')
    r = cv2.getTrackbarPos('Red','window_image')
    
    img[:] = [b, g, r]

cv2.destroyAllWindows()

Blue 51
Green 51
Red 51
Blue 102
Green 102
Red 102
Blue 153
Green 153
Red 153
Blue 204
Green 204
Red 204
Blue 255
Green 255
Red 255


**Adding a switch**

In [2]:
def switch_func(x):
    print("switch",x)

In [11]:
img = np.zeros((300,512,3), np.uint8)
cv2.namedWindow('window_image')

cv2.createTrackbar('Blue', 'window_image', 0, 255, blue)
cv2.createTrackbar('Green', 'window_image', 0, 255, green)
cv2.createTrackbar('Red', 'window_image', 0, 255, red)

switch = '0:OFF 1:ON'
cv2.createTrackbar(switch, 'window_image', 0, 1, switch_func)

while(1):
    cv2.imshow('window_image',img)
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
    b = cv2.getTrackbarPos('Blue','window_image')
    g = cv2.getTrackbarPos('Green','window_image')
    r = cv2.getTrackbarPos('Red','window_image')
    s = cv2.getTrackbarPos(switch, 'window_image')
    
    if s == 0:
        img[:] = 0 # do nothing
    else:
        img[:] = [b, g, r]
    
cv2.destroyAllWindows()

Red 51
Red 102
Green 51
Green 102
Blue 51
Blue 102
switch 1
switch 0


**Text and Grayscale at runtime**

In [5]:
def number(x):
    print("Number",x)

In [7]:
cv2.namedWindow('window_image')

cv2.createTrackbar('number', 'window_image', 10, 500, number)

switch = '0:OFF 1:ON'
cv2.createTrackbar(switch, 'window_image', 0, 1, switch_func)

while(1):
    img = cv2.imread('lena.jpg',1)
    
    num = cv2.getTrackbarPos('number','window_image')
    
    font = cv2.FONT_HERSHEY_SIMPLEX

    cv2.putText(img, str(num), (30,100), font, 2, (0,0,0), 5, cv2.LINE_AA) 
    # arguments (image, Text_to_write, starting_coor, font_face, font_size, font_color, thickness, line_type)

    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break
    
    s = cv2.getTrackbarPos(switch, 'window_image')
    
    if s==0:
        pass
    else:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    cv2.imshow('window_image',img)
        
cv2.destroyAllWindows()

switch 1
switch 0
Number 110
switch 1
switch 0
Number 210
switch 1
switch 0
switch 1


### Object detection

**Object detection and object tracking using HSV color space**

    H - Hue (select any color from value ranging from 0-360)
    S - Saturation (amount of color, value 0-1 or 0-100%)
    V - Value (brightness of color, value 0-1 or 0-100%)

Helps us to separated color luminance from color information 

In [4]:
# cv2.namedWindow("Tracking Window")

while True:
    frame = cv2.imread("smarties.png")
    
    # converting coloured into HSV image
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    # argument (frame_name, cv2.COLOR_BGR2HSV)
    
    lower_blue_color = np.array([110, 50, 50]) # value comes from exprenice 
    upper_blue_color = np.array([130, 255, 255])
    
    mask = cv2.inRange(hsv, lower_blue_color, upper_blue_color) # Threshold
    
    res = cv2.bitwise_and(frame, frame, mask = mask) # (source1, source2, mask)
    
    cv2.imshow("Image", frame)
    cv2.imshow("mask", mask)
    cv2.imshow("res", res)
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break

cv2.destroyAllWindows()

Knowing lower bound and upper bound of the color is difficult. Therefore we will use **Trackbars**

In [5]:
def nothing(x):
    pass

In [7]:
cv2.namedWindow("Tracking Window")
cv2.createTrackbar("Lower Hue", "Tracking Window", 0, 255, nothing)
cv2.createTrackbar("Lower Saturation", "Tracking Window", 0, 255, nothing)
cv2.createTrackbar("Lower Value", "Tracking Window", 0, 255, nothing)
cv2.createTrackbar("Upper Hue", "Tracking Window", 255, 255, nothing)
cv2.createTrackbar("Upper Saturation", "Tracking Window", 255, 255, nothing)
cv2.createTrackbar("Upper Value", "Tracking Window", 255, 255, nothing)


while True:
    frame = cv2.imread("smarties.png")
    
    # converting coloured into HSV image
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    # argument (frame_name, cv2.COLOR_BGR2HSV)
    
    LH = cv2.getTrackbarPos("Lower Hue", "Tracking Window")
    LS = cv2.getTrackbarPos("Lower Saturation", "Tracking Window")
    LV = cv2.getTrackbarPos("Lower Value", "Tracking Window")
    
    UH = cv2.getTrackbarPos("Upper Hue", "Tracking Window")
    US = cv2.getTrackbarPos("Upper Saturation", "Tracking Window")
    UV = cv2.getTrackbarPos("Upper Value", "Tracking Window")
    
    lower_blue_color = np.array([LH, LS, LV]) # now values come from trackbar 
    upper_blue_color = np.array([UH, US, UV])
    
    mask = cv2.inRange(hsv, lower_blue_color, upper_blue_color) # Threshold
    
    res = cv2.bitwise_and(frame, frame, mask = mask) # (source1, source2, mask)
    
    cv2.imshow("Image", frame)
    cv2.imshow("mask", mask)
    cv2.imshow("res", res)
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break

cv2.destroyAllWindows()

**For video input**

In [9]:
cap = cv2.VideoCapture(0)

fourcc = cv2.VideoWriter_fourcc(*'XVID')
output = cv2.VideoWriter("detecting_color.avi", fourcc, 20.0, (640,480))
# arguments (output_filename, fourcc, frames per second, width and height)

cv2.namedWindow("Tracking Window")
cv2.createTrackbar("Lower Hue", "Tracking Window", 0, 255, nothing)
cv2.createTrackbar("Lower Saturation", "Tracking Window", 0, 255, nothing)
cv2.createTrackbar("Lower Value", "Tracking Window", 0, 255, nothing)
cv2.createTrackbar("Upper Hue", "Tracking Window", 255, 255, nothing)
cv2.createTrackbar("Upper Saturation", "Tracking Window", 255, 255, nothing)
cv2.createTrackbar("Upper Value", "Tracking Window", 255, 255, nothing)


while True:
    BOOL, frame = cap.read()
    
    # converting coloured into HSV image
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    # argument (frame_name, cv2.COLOR_BGR2HSV)
    
    LH = cv2.getTrackbarPos("Lower Hue", "Tracking Window")
    LS = cv2.getTrackbarPos("Lower Saturation", "Tracking Window")
    LV = cv2.getTrackbarPos("Lower Value", "Tracking Window")
    
    UH = cv2.getTrackbarPos("Upper Hue", "Tracking Window")
    US = cv2.getTrackbarPos("Upper Saturation", "Tracking Window")
    UV = cv2.getTrackbarPos("Upper Value", "Tracking Window")
    
    lower_blue_color = np.array([LH, LS, LV]) # now values come from trackbar 
    upper_blue_color = np.array([UH, US, UV])
    
    mask = cv2.inRange(hsv, lower_blue_color, upper_blue_color) # Threshold
    
    res = cv2.bitwise_and(frame, frame, mask = mask) # (source1, source2, mask)
    
    cv2.imshow("Image", frame)
    cv2.imshow("mask", mask)
    
    output.write(res)
    cv2.imshow("res", res)
    
    key_pressed = cv2.waitKey(1) & 0xFF
    if key_pressed == ord('q'):
        break

cv2.destroyAllWindows()